### ISSUE TITLE
Small Firefox style issues

### ISSUE THREAD

**Issue by mariodebian** [gitbucket/gitbucket#1176]
**Impacted version**: 3.13

**Deployment mode**: standalone app with apache frontend

**Problem description**:
- New bootstrap theme looks bad in Firefox, I made the following changes in:

**webapp/assets/common/css/gitbucket.css**

1.- In issues view, col-md-9 + col-md-3 > 100% width, with this CSS looks better

```css
.main-content > .row {
    margin-left: 0;
    margin-right: 0;
}
```
2.- When view a commit in unified mode, line numers are very wide

```css
table.inlinediff td.body {
    width: 95% !important;
}

```
