### ISSUE TITLE
Sidemenu badge position in Firefox

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#1312]
## Issue
**Impacted version**: 4.5

**Problem description**:
- Sidemenu badge position is out of alignment in Firefox

![2016-10-04 11 06 58](https://cloud.githubusercontent.com/assets/1094760/19060439/4c97de8e-8a23-11e6-9a8c-12148a982621.png)

**Comment by mariodebian** [comment]
I added at bottom of .gitbucket/tmp/webapp/assets/vendors/AdminLTE-2.3.6/css/AdminLTE.min.css:

```css
.sidebar-menu > li .label, .sidebar-menu > li .badge {margin-top: -20px;}
.sidebar-menu > li.header > .label {margin-top:0;}
```

to fix it temporarily
