### ISSUE TITLE
Pull request comments layout issue in Internet Explorer

### ISSUE THREAD

**Issue by hirofw** [gitbucket/gitbucket#1366]
**Impacted version:4.6, 4.7, 4.7.1**

**Problem description**:
In Files Changed tab of Pull Requests page,
broken layout inline commment in Internet Explorer.

Internet Explorer 11
![ie](https://cloud.githubusercontent.com/assets/23052805/20878566/03389cda-bb13-11e6-8715-01ea4ae1b9c2.png)

Google chrome 54
![chrome](https://cloud.githubusercontent.com/assets/23052805/20878570/05ae6db4-bb13-11e6-8c79-98d315db5a28.PNG)

This issue may be caused by Internet Explorer doesn't work CSS:initial.
But Gitbucket uses it.

https://github.com/gitbucket/gitbucket/blob/master/src/main/webapp/assets/common/css/gitbucket.css#L1135-L1139
```css
.not-diff > .comment-box-container {
    white-space: initial;
    line-height: initial;
    padding: 10px;
}
```
