### ISSUE TITLE
(ref #1376) commit message overlap with issue number link

### ISSUE THREAD

**Issue by milligramme** [gitbucket/gitbucket#1421]
## Issue
**Impacted version**: 4.8

commit message overlap with issue number link (both long message and short message).

![screenshot 2017-01-13 13 24 25](https://cloud.githubusercontent.com/assets/294127/21918336/ac685f40-d993-11e6-8e94-93fd362dc3eb.png)

https://github.com/gitbucket/gitbucket/blob/master/src/main/webapp/assets/common/css/gitbucket.css#L300-L308

```css
td.ellipsis-cell > * {
  position: absolute;
  left: 0;
  right: 0;
  padding-right: 5px;
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}
```

`position: absolute` cause this issue.
