### ISSUE TITLE
Error with MySQL DB when migrating to v4.35.0

### ISSUE THREAD

**Issue by shinsenter** [gitbucket/gitbucket#2840]
## Issue
**Impacted version**: 4.35.0

**Deployment mode**: *Docker image : gitbucket/gitbucket:4.35.0 with MySQL driver*
```yml
version: '3'
services:
  gitbucket:
    image: gitbucket/gitbucket:4.35.0
    container_name: gitbucket
    ports:
      - "8080:8080"
    volumes:
      - "/root/.gitbucket:/gitbucket"
    environment:
      GITBUCKET_DB_URL: jdbc:mysql://mysql:3306/gitbucket?useUnicode=true&characterEncoding=utf8
      GITBUCKET_DB_USER: root
      GITBUCKET_DB_PASSWORD: hogehoge
```

**Problem description**:
MySQL Error when migrating to v4.35.0, table engine `ENGINE=InnoDB`.
v4.34.0 was working very well.
```
------------------------
LATEST FOREIGN KEY ERROR
------------------------
2021-08-03 06:46:13 0x7fe76c2af700 Error in foreign key constraint of table gitbucket/#sql-1_3:
 FOREIGN KEY (`USER_NAME`, `REPOSITORY_NAME`) REFERENCES REPOSITORY (`USER_NAME`, `REPOSITORY_NAME`):
Cannot find an index in the referenced table where the
referenced columns appear as the first columns, or column types
in the table and the referenced table do not match for constraint.
Note that the internal storage type of ENUM and SET changed in
tables created with >= InnoDB-4.1.12, and such columns in old tables
cannot be referenced by such columns in new tables.
Please refer to http://dev.mysql.com/doc/refman/5.7/en/innodb-foreign-key-constraints.html for correct foreign key definition.
```

Above error occured with this line of migration script:
https://github.com/gitbucket/gitbucket/blob/master/src/main/resources/update/gitbucket-core_4.35.xml#L27
```xml
  <addForeignKeyConstraint constraintName="IDX_WEB_HOOK_FK0" baseTableName="WEB_HOOK" baseColumnNames="USER_NAME, REPOSITORY_NAME" referencedTableName="REPOSITORY" referencedColumnNames="USER_NAME, REPOSITORY_NAME"/>
```
Running other migration scripts with `referencedTableName` also failed.
